### ISSUE TITLE
Files

### ISSUE THREAD

**Issue by chendo** [chendo/ping-statsd#1]
![screenshot 2016-10-06 23 17 13](https://cloud.githubusercontent.com/assets/2661/19151915/14f063a8-8c1b-11e6-856a-76f2cfbabe6a.png)
![screenshot 2016-10-06 23 19 12](https://cloud.githubusercontent.com/assets/2661/19151955/4f7ec7ee-8c1b-11e6-9528-d65c927aa615.png)

**Comment by humiaozuzu** [comment]
@chendo May I know what is the name of the Admin UI in the picture?

**Comment by chendo** [comment]
@humiaozuzu it's Datadog
